name: Deploy package
# Event triggers for github workflow
on:
  release:
    types: [released] # only run it on released. Otherwise it is triggered 3 times.

env:
  # Run all pip install's from Van Oord PyPi
  PIP_INDEX_URL: ${{ secrets.ADO_PYPI_DOWNLOAD_URL }}

jobs:
  build:
    name: Deploy package
    runs-on: ubuntu-latest
    steps:
    # Checkout
    - uses: actions/checkout@v3
    # Setup Python
    - name: Setup python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Upgrade pip
    - run: python -m pip install --upgrade pip
    # Install build tools
    - run: python -m pip install --upgrade build
    # Build the package
    - run: python -m build
    # Show the dist folder
    - run: ls ./dist

    # Deploy to Azure artifacts
    - name: Update packages to support upload
      run: python -m pip install --upgrade twine keyring
    - name: Upload package to the AzureDevOps artifacts
      run: twine upload --repository-url ${{ secrets.ADO_PYPI_UPLOAD_URL }} -u '${{ secrets.ADO_PYPI_UPLOAD_ACC }}' -p ${{ secrets.ADO_PYPI_UPLOAD_PAT }} dist/* --verbose
